/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectacp;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Arrays;
/**
 *
 * @author Lenovo
 */
public class AddRegularly extends javax.swing.JFrame {
    protected  ArrayList<String> doRegularly = new ArrayList<String>();
    protected  ArrayList<String> timeRegularly = new ArrayList<String>();
    protected  ArrayList<String> dayRegularly = new ArrayList<String>();
    protected  ArrayList<String> userSelec;
    protected int indexRegularly, indexSometime;
    protected  ArrayList<String> doSometime = new ArrayList<String>();
    protected  ArrayList<String> dateSometime = new ArrayList<String>();
    protected  ArrayList<String> timeSometime = new ArrayList<String>();
    protected   FindDay daySometime;
    protected  int testResultRegularly;
    final protected String fileRegularlyAddress = "D:\\\\regularlydata.txt";
    
    protected int testSometimeFile;
    protected JLabel msg;
    /**
     * Creates new form AddRegularly
     */
    public AddRegularly() {
        initComponents();
        routine.setFont(new Font("tahoma",Font.PLAIN, 16));
        time.setFont(new Font("tahoma",Font.PLAIN, 16));
    }
    
    private void saveRoutineToFile(String a){
         try{
            Path file = Paths.get(fileRegularlyAddress);
            BufferedWriter outputData = Files.newBufferedWriter(file,StandardCharsets.UTF_8, StandardOpenOption.APPEND);
            outputData.write(a);
            outputData.close();
            JOptionPane.showMessageDialog(null,"Comple");
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,"No file");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        routine = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dayList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Routine");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Add your routine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        routine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        routine.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("save");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TH NiramitIT๙ ", 1, 24)); // NOI18N
        jLabel1.setText("*Routine");

        jLabel2.setFont(new java.awt.Font("TH NiramitIT๙", 1, 24)); // NOI18N
        jLabel2.setText("*Time to do");

        jLabel3.setFont(new java.awt.Font("TH NiramitIT๙", 1, 24)); // NOI18N
        jLabel3.setText("*Day");

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("( *E.g 13.10 )");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("cancel");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dayList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        dayList.setSelectionBackground(new java.awt.Color(51, 255, 255));
        jScrollPane1.setViewportView(dayList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(routine, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
   /*     userSelec = (ArrayList<String>) dayList.getSelectedValuesList();
        System.out.println(Arrays.toString(userSelec.toArray()));
        System.out.println(userSelec.get(0));*/
        
        if (routine.getText().isEmpty() || time.getText().isEmpty() || dayList.getSelectedValuesList().isEmpty()){
            JOptionPane.showMessageDialog(null,"Plaese Enter Data");
        } else {
            String regularly = routine.getText().trim();
            String timeRoutine = time.getText().trim();
            ArrayList<String> dayRoutine = (ArrayList<String>) dayList.getSelectedValuesList(); //day.getSelectedItem().toString();
            
            Check test = new Check();
            for (int c = 0;  c < dayRoutine.size(); c++){
                 testResultRegularly = test.CheckwhattodoRegularly(timeRoutine, dayRoutine.get(c));
                 if (testResultRegularly == 0){
                      doRegularly = test.getWhatToDo();
                      indexRegularly = test.getIndex();
                     break;
                 }
            }
          
            test.setFileName("D:\\\\sometimedata.txt");
            test.fileToArray();
            doSometime = test.getWhatToDo();
            dateSometime = test.getDateToDo();
            timeSometime = test.getTimeToDo();

            testSometimeFile = 1;
            for (int j = 0; j < dayRoutine.size(); j++){
                for (int i =0; i < dateSometime.size(); i++){
                 daySometime = new FindDay(dateSometime.get(i));
                 if (timeRoutine.equalsIgnoreCase(timeSometime.get(i))){
                     if (dayRoutine.get(j).equalsIgnoreCase(daySometime.findDayOfWeek())){
                         testSometimeFile = 0;
                         indexSometime = i;
                         break;
                      } 
                 }      
            }
            }
            
            if (testResultRegularly == 0 || testSometimeFile == 0 ){
                 time.setText("");
                if (testResultRegularly == 0){
                    msg = new JLabel("There is something to do: \n " + doRegularly.get(indexRegularly));
                    msg.setFont(new Font("tahoma",Font.PLAIN, 20));
                }
                else if (testSometimeFile == 0){
                    msg = new JLabel("There is something to do: \n " + doSometime.get(indexSometime));
                    msg.setFont(new Font("tahoma",Font.PLAIN, 20));
                }       
                JOptionPane.showMessageDialog(null,msg); 
            } else{
                String regularlyData = DataRegularly(regularly, timeRoutine, dayRoutine);
                saveRoutineToFile(regularlyData);
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        routine.setText("");
        time.setText("");
        dayList.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    public String DataRegularly(String event, String time, ArrayList<String> data) {
        String dataRegularly = "";
        for (int i = 0;  i < data.size();  i++){
            dataRegularly += data.get(i);
            if (i != data.size() - 1){
                dataRegularly += ",";
            }
        }
        return event + "-" + time + "-" + dataRegularly + "\n";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRegularly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRegularly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRegularly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRegularly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRegularly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> dayList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField routine;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
